"""Source/assumption report and actual-model gallery for Waveshare references."""
from pathlib import Path
import json,csv,html

def generate(root):
    g=json.loads((root.parent/'config/geometry.json').read_text());w=g.get('waveshare_detail',{})
    if not w.get('enabled'):return ''
    rev=g['revision'];geo=json.loads((root/'reports/waveshare_geometry.json').read_text());val=json.loads((root/'reports/waveshare_validation.json').read_text());esc=html.escape
    study=root/'studies/waveshare_detail';study.mkdir(exist_ok=True)
    with (study/'arrival_measurement.csv').open('w') as f:
        wr=csv.writer(f);wr.writerow(['photo_reference_NOT_schematic_ref','side','center_u_mm','center_v_mm','width_mm','height_in_plane_mm','projection_mm','xy_uncertainty_mm','height_uncertainty_mm','evidence','measured_width_mm','measured_height_mm','measured_projection_mm','notes'])
        for p in w['cam']['parts']:wr.writerow([p['reference'],p['side'],*p['center_uv_mm'],p['width_mm'],p['height_v_mm'],p['projection_mm'],p['xy_uncertainty_mm'],p['height_uncertainty_mm'],p['evidence'],'','','',p.get('value','')])
    clash=val['intersections'];detail='未修改打印件；相机座局部适配等待确认。' if not w.get('approved_mount_change_ids') else '相机座已按确认方案局部适配。'
    notice=('照片重建的OV3660方形模组与原前壳内侧、相机座有3对实体交集。' if clash else '本轮微雪重建器件的名义实体未检出穿插。')+detail+'照片尺寸误差、实物公差和真实排线仍未验证。'
    rows=[('1.85寸圆屏 / SKU35079','原厂STEP，原始111实体，1:1保留','仅增加材料区分与可编辑子件。实体107/108连接器三角化非流形，检查使用保守代理；采购版本与9.1/9.35mm图纸差异待复核。'),('CAM / SKU33700','官方37×37mm、R2.25、32.6×32.6mm孔网格','双面芯片、SD座、FPC座、USB-C、1.25/1.0接口、按键及可见小封装按官方照片重建。板厚1.6±0.4mm、孔径2.7±0.3mm为模型假设。'),('双MEMS麦克风','原板自带，按照片示意外壳与声孔','没有新增独立麦克风或导管。封装型号和声孔位置需实测。'),('OV3660相机','匹配33700的官方版本照片','方形基座8.2×8.2mm、镜头座7.8×7.8mm等均为照片估算；宽高约±0.6mm，深度约±1mm，不是原厂公差。镜头焦距3.2mm不当作机械厚度。')]
    table='<table><tr><th>部件</th><th>依据</th><th>精度边界</th></tr>'+''.join('<tr>'+''.join('<td>'+esc(c)+'</td>' for c in r)+'</tr>' for r in rows)+'</table>'
    cards=''.join(f'<figure><a href="{name}.png"><img src="{name}.png?revision={rev}" alt="{title}"></a><figcaption>{title}</figcaption></figure>' for name,title in [('cam_sd','CAM：SD、相机接口与双麦面'),('cam_ic','CAM：ESP32、音频和连接器面'),('camera','OV3660：紧凑方形模组'),('lcd_back','LCD：原厂背板和接插件'),('head','同一套几何在头部的布置'),('camera_fit','相机与当前安装座的局部关系')])
    linked_sources=json.loads((root.parent/w['source_manifest']).read_text())['sources'];source_html=''.join(f'<li><a href="{esc(r["url"])}">{esc(Path(r["file"]).name)}</a></li>' for r in linked_sources)
    hits='<table><tr><th>器件</th><th>相交对象</th><th>交集体积（模型）</th></tr>'+''.join(f'<tr><td>{r["part"]}</td><td>{r["obstacle"]}</td><td>{r["volume_mm3"]:.1f} mm³</td></tr>' for r in clash)+'</table>' if clash else ''
    page=f'''<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MORI {rev} · 微雪部件</title><style>body{{max-width:1200px;margin:30px auto;padding:0 24px 60px;background:#edf0ef;color:#22332f;font:16px/1.75 system-ui}}h1{{font-size:38px;line-height:1.3}}a{{color:#216556}}.grid{{display:grid;grid-template-columns:1fr 1fr;gap:20px}}figure{{margin:0;background:white;border-radius:10px;overflow:hidden}}img{{width:100%;display:block}}figcaption{{padding:12px}}table{{border-collapse:collapse;width:100%;background:white}}td,th{{padding:12px;border:1px solid #ced7d1;text-align:left}}.notice{{padding:18px;background:#fff1d7;border-radius:10px}}.links{{display:flex;gap:20px;flex-wrap:wrap;margin:20px 0}}@media(max-width:700px){{.grid{{grid-template-columns:1fr}}}}</style><a href="../../index.html?revision={rev}">← MORI</a><h1>微雪部件：官方尺寸＋照片重建</h1><p>{rev} · 所有预览来自实际Blender模型。板卡使用本来尺寸，未缩放塞入支架。</p><div class="links"><a href="../../mori_v1_2.blend">当前总装 Blender</a><a href="../../mori_electronics_detail.blend">微雪部件检视 Blender</a><a href="arrival_measurement.csv">到货尺寸复核表</a></div><p>详细文件默认打开 <b>MORI_Waveshare_Bench</b> 场景，每个子件可单独选择；<b>MORI_PCB_Component_Detail</b>保留真实装配坐标。检视台的平移、转向仅用于展示。未装配的相机排线平展参考单独标注，不代表线束能接通。</p><div class="notice">{notice}</div><h2>来源与精度</h2>{table}<p>CAM细小封装的PH编号是照片定位编号，未冒充原理图位号。未还原铜线、全部丝印、焊锡或芯片内部；估算范围是建模的不确定度，不是制造商公差。颜色用于区分材料，不能据此判断尺寸已验证。</p><div class="grid">{cards}</div><h2>实际检查</h2><p>范围与来源检查：{val['source_scope_status']}。微雪名义刚性适配：{val['nominal_fit']}。原始圆屏网格保持：{val['scope']['LCD_original_mesh_unchanged']}。其余未授权部件变化：{len(val['scope']['unexpected_changes'])}。</p>{hits}<p>整机运动是有限姿态采样；固定相连的打印座仍须按静态检查判定。未做实测、打印强度或声学认证。</p><div class="links"><a href="../../reports/waveshare_validation.json">检查明细</a><a href="../../reports/waveshare_geometry.json">部件与来源元数据</a><a href="render_manifest.json">渲染来源</a><a href="../../reports/waveshare_commands.json">执行命令</a></div><h2>官方资料</h2><ul>{source_html}</ul></html>'''
    (study/'index.html').write_text(page)
    md=f'# 微雪器件精细模型 · {rev}\n\n'+notice+'\n\n| 部件 | 依据 | 边界 |\n|---|---|---|\n'+'\n'.join('| '+' | '.join(r)+' |' for r in rows)+'\n\n照片定位PH编号不是原理图位号；细小封装并非完整电气BOM。颜色不表示已实测。走线延后，无新增打印件、孔或紧固件。\n\n[实际模型预览](../studies/waveshare_detail/index.html) · [到货复核表](../studies/waveshare_detail/arrival_measurement.csv) · [几何检查](waveshare_validation.json)\n'
    (root/'reports/微雪部件模型.md').write_text(md)
    return f'<section id="waveshare-detail"><h2>微雪器件模型已细化</h2><p>{notice}</p><div class="links"><a href="studies/waveshare_detail/index.html?revision={rev}">模型、官方来源与精度边界</a><a href="mori_electronics_detail.blend">独立器件检视 Blender</a></div><div class="grid"><a class="card" href="studies/waveshare_detail/index.html"><img src="studies/waveshare_detail/cam_sd.png?revision={rev}"><h3>CAM 双面装件及板载麦克风</h3></a><a class="card" href="studies/waveshare_detail/index.html"><img src="studies/waveshare_detail/lcd_back.png?revision={rev}"><h3>圆屏原厂实体与接插件</h3></a></div></section>'

if __name__=='__main__':print(generate(Path(__file__).resolve().parents[1])[:120])
