"""User-adopted M1.43 repairs 1–6; dimensions from geometry.json only.

Wheel bearing/shaft/spacer changes are generated by the original wheel phase
using the updated wheel_interface. This phase handles the remaining local edits.
"""
from common import *
from validate import Solid
from monocoque_structure import obj,source_build
from interface_completion import axial,repair_quantized_triangles
from layout_cleanup import mm_mesh

def boxm(lo,hi):
    return manifold.Manifold.cube((np.array(hi)-lo).tolist()).translate(lo)

def replace(name,m):
    o=obj(name)
    if o.get('mori_owner')!=OWNER:raise RuntimeError('Unowned mesh: '+name)
    m=m.set_tolerance(.00001).simplify(.00001);d=m.to_mesh64()
    v=np.asarray(d.vert_properties[:,:3],dtype=np.float32).astype(float)
    f=np.array(d.tri_verts,dtype=np.int64);v,f,ops,bad=repair_quantized_triangles(v,f)
    if bad:raise RuntimeError('Mesh degeneracy after repair: '+name)
    m=manifold.Manifold(manifold.Mesh64(np.array(v,dtype=np.float64,order='C'),np.array(f,dtype=np.uint64,order='C')))
    if m.status()!=manifold.Error.NoError:raise RuntimeError('Nonmanifold repair: '+name)
    mats=list(o.data.materials);tmp=mm_mesh('issue_fix_clean_mesh',m)
    o.data=tmp.data.copy();o.data.materials.clear()
    for material in mats:o.data.materials.append(material)
    o.matrix_world=Matrix.Identity(4);SOLIDS.pop(o.name,None);bpy.data.objects.remove(tmp,do_unlink=True)
    o['assembly_issue_revision']=P['revision']
    return o,ops

def shell_restore_zone(q):
    zone=manifold.Manifold()
    for sx in [-1,1]:
        for sy in [-1,1]:
            x=sorted(sx*v for v in q['old_restore_abs_x_mm']);y=sorted(sy*v for v in q['old_restore_abs_y_mm'])
            zone+=boxm([x[0],y[0],0],[x[1],y[1],q['old_restore_max_z_mm']])
    return zone

def relocate_body_seam():
    q=P.get('assembly_issue_fixes',{})
    if not q.get('enabled'):return
    q=q['body_seam'];b=source_build()
    o=b.body_outer('seam_repair_outer');outer=Solid(o).m;bpy.data.objects.remove(o,do_unlink=True)
    o=b.body_outer('seam_repair_inner',P['shell_thickness_mm']);inner=Solid(o).m;bpy.data.objects.remove(o,do_unlink=True)
    skin=outer-inner;zones=shell_restore_zone(q);split=D['body_z'];gap=P['seam_gap_mm']/2
    forms={}
    for n,lo,hi in [('Body_Upper',split+gap,300),('Body_Lower',0,split-gap)]:
        forms[n]=(Solid(obj(n)).m-zones)+(skin^zones^boxm([-200,-200,lo],[200,200,hi]))
    for i,(x,y) in enumerate(q['xy_mm']):
        for n,label in [('Body_Upper','upper'),('Body_Lower','lower')]:
            lug=axial(q['lug_radius_mm'],q[label+'_height_mm'],[x,y,q[label+'_center_z_mm']],[0,0,1])
            rx=sorted([x,math.copysign(q['rib_end_abs_x_mm'],x)]);z=q[label+'_rib_z_mm'];dy=q['rib_width_mm']/2
            lug+=boxm([rx[0],y-dy,z[0]],[rx[1],y+dy,z[1]])
            forms[n]+=lug^outer
        forms['Body_Upper']-=axial(q['upper_pilot_mm']/2,q['upper_pilot_length_mm'],[x,y,q['upper_pilot_center_z_mm']],[0,0,1])
        for label in ['hole','recess']:
            forms['Body_Lower']-=axial(q['lower_'+label+'_radius_mm'],q['lower_'+label+'_length_mm'],[x,y,q['lower_'+label+'_center_z_mm']],[0,0,1])
        # Deburr the counterbore's exterior breakout only, below its unchanged
        # head-bearing plane. This removes a submillimetre feathered mouth edge.
        lead=q.get('lower_recess_mouth_lead_mm',0)
        if lead:
            top=q['lower_recess_center_z_mm']+q['lower_recess_length_mm']/2;r=q['lower_recess_radius_mm']
            forms['Body_Lower']-=manifold.Manifold.cylinder(lead+.01,r+lead+.01,r-.001,96).translate([x,y,top-lead])
        # Catalogue inserts are recreated next by interface_completion.
        n=f'Shell_Screw_{i}';a=Solid(obj(n));c=(a.lo+a.hi)/2
        replace(n,a.m.translate([x-c[0],y-c[1],0]))
    for n,m in forms.items():replace(n,m)

def hex_x(af,depth,center):
    rot=np.array([[0,0,1],[1,0,0],[0,1,0]])
    return manifold.Manifold.cylinder(depth,af/math.sqrt(3),af/math.sqrt(3),6,center=True).transform(np.c_[rot,center])

def apply_assembly_issue_fixes():
    q=P.get('assembly_issue_fixes',{})
    if not q.get('enabled'):return
    assembled();bpy.context.view_layer.update();repairs=[]
    o,ops=replace('Display_Frame',Solid(obj('Display_Frame')).m+boxm(*q['camera_floor']['fill_bounds_mm']));repairs.append({'id':o.name,'mesh_repairs':ops})
    file=ROOT/'reports/prearrival_geometry.json';report=json.loads(file.read_text());rows={r['id']:r for r in report['servo_ears']}
    p=q['pitch_nut'];r=rows[p['id']];face=np.array(r['ear_top_mm']);z=face[2];m=Solid(obj('Pitch_Yoke')).m
    restore=axial(p['old_pocket_restore_radius_mm'],p['old_pocket_restore_depth_mm'],[p['old_pocket_center_x_mm'],0,z],[1,0,0],64)^boxm(*p['restore_bounds_mm'])
    m+=restore
    m-=axial(p['bearing_reopen_radius_mm'],p['bearing_reopen_length_mm'],[p['bearing_reopen_center_x_mm'],0,D['head_z']],[1,0,0],64)
    m+=axial(p['old_bore_restore_radius_mm'],p['old_bore_restore_length_mm'],[p['old_bore_restore_center_x_mm'],0,z],[1,0,0])^boxm(*p['restore_bounds_mm'])
    center=np.array([p['center_x_mm'],0,z]);pc=np.array([p['pocket_center_x_mm'],0,z]);half=p['pocket_depth_mm']/2
    # User-approved follow-up: a continuous higher top edge and open pocket
    # underside replace the candidate's 0.2/0.5mm lips. Hardware stays put.
    if p.get('open_floor_user_approved'):
        sy=p['upper_pad_half_width_y_mm'];sz=p['upper_pad_old_half_height_mm']
        m+=boxm([p['upper_pad_start_x_mm'],-sy,z-sz],[r['seat_point_mm'][0],sy,z+sz+p['upper_roof_addition_mm']])
    m-=hex_x(p['pocket_AF_mm'],p['pocket_depth_mm'],pc)+boxm([pc[0]-half,0,z-p['entry_half_height_mm']],[pc[0]+half,p['entry_positive_y_mm'],z+p['entry_half_height_mm']])
    if p.get('open_floor_user_approved'):
        m-=axial(1.1,14,[r['seat_point_mm'][0]-6.99,0,z],[1,0,0])
        m-=boxm([pc[0]-half,p['nut_floor_open_y_min_mm'],z+p['nut_floor_open_z_from_axis_mm']],[pc[0]+half,p['nut_floor_open_y_max_mm'],z+p['nut_floor_open_top_from_axis_mm']])
    replace(p['id']+'_Nut',hex_x(p['AF_mm'],p['thickness_mm'],center)-axial(1,2,center,[1,0,0]))
    length=p['screw_length_mm'];hh=p['screw_head_height_mm']
    bolt=axial(1,length+.02,face+[-(length-.02)/2,0,0],[1,0,0])+axial(p['screw_head_diameter_mm']/2,hh,face+[hh/2,0,0],[1,0,0])
    bolt-=axial(p['screw_drive_AF_mm']/math.sqrt(3),p['screw_drive_depth_mm']+.02,face+[hh-p['screw_drive_depth_mm']/2+.01,0,0],[1,0,0],6)
    o,_=replace(p['id']+'_Screw',bolt);o['label_zh']='M2×8 内六角俯仰上耳螺钉';o['fastener_spec']=p['screw_specification'];o['data_status']='VENDOR_DOCUMENTED';o['source_url']=p['screw_source_url'];o['model_fidelity']='DIN912 M2 nominal head and socket; thread omitted; source family dimensions, physical fastener unmeasured'
    r.update(screw_length_mm=length,nut_center_mm=center.tolist(),nut_bearing_mm=(center+[p['thickness_mm']/2,0,0]).tolist(),recess_mm=p['pocket_depth_mm'],nut_entry_direction=[0,1,0],screw_thread_projection_beyond_nut_mm=float(center[0]-p['thickness_mm']/2-(face[0]-length)))
    p=q['yaw_nut'];r=rows[p['id']];seat=r['seat_point_mm'][2];center=np.array(r['nut_center_mm']);pc=np.array([center[0],center[1],seat+p['pocket_center_from_seat_mm']])
    lo,hi=[np.array(v)+[0,0,seat] for v in p['pad_bounds_from_seat_mm']]
    m+=axial(p['restore_radius_mm'],p['restore_depth_mm'],pc,[0,0,1],6)^boxm(lo,hi)
    m-=axial(p['pocket_AF_mm']/math.sqrt(3),p['pocket_depth_mm'],pc-[0,0,.005],[0,0,1],6)
    m-=boxm([-p['entry_width_mm']/2,center[1],seat+p['entry_bottom_from_seat_mm']],[p['entry_width_mm']/2,p['entry_y_end_mm'],seat+p['entry_top_from_seat_mm']])
    m-=axial(p['through_radius_mm'],p['through_length_mm'],[center[0],center[1],seat-3],[0,0,1])
    r['nut_entry_direction']=[0,1,0]
    o,ops=replace('Pitch_Yoke',m);repairs.append({'id':o.name,'mesh_repairs':ops});save_json(file,report)
    p=q['drive_nuts'];m=Solid(obj('Drive_Bridge')).m
    current_fasteners={r['id']:r for r in json.loads((ROOT/'studies/interface_completion/fastener_current.json').read_text())}
    for n in p['ids']:
        a=Solid(obj(n));c=(a.lo+a.hi)/2;c[2]=p['center_z_mm'];sy=1 if c[1]>0 else -1;y=sorted([c[1],sy*p['entry_abs_y_mm']])
        depth=p['pocket_top_z_mm']-p['pocket_bottom_z_mm'];mid=c.copy();mid[2]=(p['pocket_top_z_mm']+p['pocket_bottom_z_mm'])/2
        rz0=p['restore_bottom_z_mm'];rz1=p['restore_top_z_mm'];restore_mid=[mid[0],mid[1],(rz0+rz1)/2]
        zone=boxm([mid[0]-4,mid[1]-4,rz0-.025],[mid[0]+4,mid[1]+4,rz1+.025])
        # The approved entry study used documented DIN934 nuts and contained
        #4.2AF pockets. Restore those dependencies, not the old generic2.4mm nut.
        m+=axial(p['restore_radius_mm'],rz1-rz0,restore_mid,[0,0,1],p['restore_segments'])^(m^zone).hull()
        m-=axial(p['pocket_AF_mm']/math.sqrt(3),depth+p['pocket_depth_margin_mm'],mid,[0,0,1],6)
        m-=axial(1.2,24,c,[0,0,1])
        nut=axial(p['AF_mm']/math.sqrt(3),p['thickness_mm'],c,[0,0,1],6)-axial(1,p['thickness_mm']+.1,c,[0,0,1])
        o,_=replace(n,nut);o['label_zh']='M2 A2六角螺母 / DIN934尺寸基准';o['category']='PURCHASED_REFERENCE';o['data_status']='VENDOR_DOCUMENTED';o['source_url']=p['source_url'];o['model_fidelity']='DIN934 maximum AF4x1.6 envelope; chamfer/thread omitted; physical fit unmeasured'
        sn=n.replace('_Nut','_Screw');f=current_fasteners[sn];axis=np.array(f['extracted_axis_outward']);face=np.array(f['tool_start_mm'])-axis*f['nominal_head_height_mm'];length=p['screw_length_mm']
        bolt=axial(1,length+.02,face-axis*(length-.02)/2,axis)+axial(1.75,1.4,face+axis*.7,axis)
        o,_=replace(sn,bolt);o['label_zh']='GB823 M2×8 轮驱托板螺钉';o['category']='PURCHASED_REFERENCE';o['data_status']='VENDOR_DOCUMENTED';o['model_fidelity']='Documented nominal envelope; thread helix and drive recess omitted';o['source_url']=P['interface_completion']['M2_screw_source']
        entry_z=c[2]+p['entry_center_z_offset_mm']
        m-=boxm([c[0]-p['entry_width_mm']/2,y[0],entry_z-p['entry_height_mm']/2],[c[0]+p['entry_width_mm']/2,y[1],entry_z+p['entry_height_mm']/2])
    o,ops=replace('Drive_Bridge',m);repairs.append({'id':o.name,'mesh_repairs':ops})
    # Small Boolean quantization artifacts can occur on a rebuilt saddle.
    o,ops=replace('Motor_Retainer',Solid(obj('Motor_Retainer')).m);repairs.append({'id':o.name,'mesh_repairs':ops})
    for name in ['Wheel_Axle_L','Wheel_Axle_R']:
        o,ops=replace(name,Solid(obj(name)).m);repairs.append({'id':o.name,'mesh_repairs':ops})
    save_json(ROOT/'reports/assembly_issue_fixes.json',{'revision':P['revision'],'status':'NOT_TESTED','applied_items':[1,2,3,4,5,6],'configuration':'config/geometry.json#/assembly_issue_fixes','mesh_repairs':repairs,'part_count_change':0,'native_PCB_changed':False,'manufacturing_release':False})
    print('ASSEMBLY_ISSUES_1_TO_6_APPLIED',flush=True)

def change_regions():
    """Independent conservative edit bounds for cumulative regression audits."""
    q=P.get('assembly_issue_fixes',{})
    if not q.get('enabled'):return {}
    reg={'Display_Frame':boxm([-6.32,27.49,257.34],[6.32,30.51,259.811]),
         'Pitch_Yoke':boxm([-42.01,-8.01,225.99],[-32.84,8.01,236.01])}
    # The yaw rear seat stays at the original documented ear position.
    rows=json.loads((ROOT/'reports/prearrival_geometry.json').read_text())['servo_ears'];r=next(r for r in rows if r['id']==q['yaw_nut']['id']);seat=r['seat_point_mm'][2];y=r['nut_center_mm'][1]
    reg['Pitch_Yoke']+=boxm([-2.57,y-2.57,seat-4.51],[2.57,-6.13,seat-2.57])+axial(1.11,12.02,[0,y,seat-3],[0,0,1],64)
    reg['Pitch_Yoke']+=axial(6.27,16.04,[-39,0,D['head_z']],[1,0,0],64)
    if q['pitch_nut'].get('open_floor_user_approved'):
        p=q['pitch_nut'];r=next(r for r in rows if r['id']==p['id']);z=r['seat_point_mm'][2]
        reg['Pitch_Yoke']+=boxm([-36.02,-5.52,z-6.02],[r['seat_point_mm'][0]+.02,5.52,z+3.32])
    w=P['wheel_interface'];b=q['wheel_bearing'];region=manifold.Manifold()
    for sign in [-1,1]:
        a=b['old_inner_center_abs_x_mm']-w['bearing_width_mm']/2-w['bearing_seat_axial_margin_mm']-.02
        z=w['bearing_centers_abs_x_mm'][0]+w['bearing_width_mm']/2+w['bearing_seat_axial_margin_mm']+.02
        region+=axial(w['bearing_seat_nominal_diameter_mm']/2+.02,z-a,[sign*(z+a)/2,0,D['wheel_z']],[1,0,0])
    reg['Drive_Bridge']=region;reg['Motor_Retainer']=region
    for sign in [-1,1]:
        for y in [-8,8]:
            c=[sign*P['structure']['simple_modules']['frame_joint_abs_x_mm'],y,62.25];ys=sorted([y,math.copysign(18,y)])
            reg['Drive_Bridge']+=boxm([c[0]-2.51,ys[0]-.01,61.14],[c[0]+2.51,ys[1]+.01,63.21])
            reg['Drive_Bridge']+=axial(2.93,3.75,c[:2]+[61.55],[0,0,1],96)+axial(1.21,24.02,c,[0,0,1])
    b=q['body_seam'];region=shell_restore_zone(b)
    for x,y in b['xy_mm']:
        region+=boxm([-b['rib_end_abs_x_mm']-.02,y-b['lug_radius_mm']-.02,0],[b['rib_end_abs_x_mm']+.02,y+b['lug_radius_mm']+.02,107.02])
    reg['Body_Upper']=region;reg['Body_Lower']=region
    return reg
